### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by danroberts** [moagrius/copyCss#1]
Can you provide a licence please? Mit is preferable but it's obviously up to you.

**Comment by BerkerYuceer** [comment]
I agree with dan! An MIT licence would be great and allow us to use this feature and redirect all credits to you. 
To add MIT licence see the following links:
- http://opensource.org/licenses/MIT
- http://stackoverflow.com/questions/1229620/how-do-i-release-a-project-under-the-mit-license

**Comment by moagrius** [comment]
added.
