### ISSUE TITLE
Ignore defaults.

### ISSUE THREAD

**Issue by Hypercubed** [moagrius/copyCss#6]
Hello.  I'm using this plugin in an angular module that downloads SVG elements.  This plugin ensure that all css styles are copied to a clone of the svg before downloading.  Using http://www.w3.org/TR/SVG/propidx.html I am able to restrict the styles to only those that are relevant to svg.  However, this still copies every style on the list.  Any idea how to copy only the non-default values?  Can jquery determine the default style?  Maybe if the user supplies a list of default styles for each style on the only list?

**Comment by moagrius** [comment]
I'm not sure, but I'd think you'd have to do it manually by providing a white-list of all styles you wanted to copy.

Sorry I couldn't be more help.

**Comment by Hypercubed** [comment]
I suggest if the white list is a hash getStyle returns a hash of styles whose names are the keys and values do not match the value.  For example:

```
{
  color: '#333';
  background-color: '#fff';
}
```

Should return the computed `color` and `background-color` if they do not match the value values `#333` and `#fff` respectively.  I guess you can also use the exclude array somehow.  Again, just a suggestion.

**Comment by moagrius** [comment]
I'd personally probably extend (or create a new function) rather than change existing functionality - feel free to use whatever's helpful.

**Comment by Hypercubed** [comment]
I'm now using a white list ignoring defaults (see here: https://github.com/Hypercubed/angular-downloadsvg-directive/blob/master/angular-downloadsvg-directive.js#L78 ).  While I'm not using copycss in the end it helped me get started.  Thank you.
